Task/improve modals
bycza-zagroda/track-expenses-app-frontend pull request #101
Opened 2023-02-12 09:37 UTC by Bartexs

Closes #94 

---

I confirm that (check also those that do not apply to this PR):
- [X] New code is covered with tests and coverage requirements are met
- [X] All tests are passing
- [X] Build is not failing
- [X] Mobile version of new functionality is displayed properly
- [X] All linter issues are resolved
- [X] All conflicts are resolved and branch is rebased on top of the up-to-date parent branch
- [X] All issue requirements are implemented
- [X] At least two reviewers are assigned
- [X] I'm assigned as a assignee
- [X] PR is linked to the related issue

2023-02-13 14:50 UTC, mirekgab approved these changes, later dismissed

2023-02-13 22:01 UTC, purbanski-deftcode requested changes

2023-02-13 22:01 UTC, purbanski-deftcode commented on src/assets/styles/components/modals.scss
> +    min-width: 300px;
You should use global config for this:
https://material.angular.io/components/dialog/overview#specifying-global-configuration-defaults
https://material.angular.io/components/dialog/api#MatDialogConfig

2023-02-13 22:01 UTC, purbanski-deftcode commented on src/assets/styles/components/modals.scss
> +
Please remove 2 out of 3 empty lines in the end of the file

2023-02-13 22:01 UTC, purbanski-deftcode commented on src/assets/styles/components/modals.scss
> +div:has( + mat-form-field) {
Remov space before `+`

2023-02-13 22:01 UTC, purbanski-deftcode commented on src/assets/styles/components/modals.scss
> +    padding-top:30px;
Please add space after `:`

2023-02-13 22:01 UTC, purbanski-deftcode commented on src/assets/styles/components/modals.scss
> +    padding-top:30px;
And my bad, 30px seems to be too much, lets go with 20px :)

2023-02-14 20:15 UTC, purbanski-deftcode approved these changes

2023-02-14 20:18 UTC, Iwona007 approved these changes

2023-02-14 20:20 UTC, merged