Bug/122 adjust validation for transaction amount
bycza-zagroda/track-expenses-app-frontend pull request #127
Opened 2023-03-20 18:33 UTC by tomektomek321

Closes #122 

---

I confirm that (check also those that do not apply to this PR):
- [ ] New code is covered with tests and coverage requirements are met
- [ ] All tests are passing
- [ ] Build is not failing
- [ ] Mobile version of new functionality is displayed properly
- [ ] All linter issues are resolved
- [ ] All conflicts are resolved and branch is rebased on top of the up-to-date parent branch
- [ ] All issue requirements are implemented
- [ ] At least two reviewers are assigned
- [ ] I'm assigned as a assignee
- [ ] PR is linked to the related issue

2023-03-20 19:45 UTC, purbanski-deftcode requested changes

2023-03-20 19:45 UTC, purbanski-deftcode commented on src/app/common/utils/pipes/transaction-amount.pipe.ts
>      if(value === 0) {
```suggestion
    if (value === 0) {
      return '0.00';
    }
```

2023-03-20 19:45 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.html
> +          <span [ngClass]="element.amount === 0 ? 'amount--0' : (element.type === walletTransactionType.Expense ? 'amount--expense' : 'amount--income')">
```suggestion
          <span [ngClass]="element.amount === 0 ? 'amount--zero' : (element.type === walletTransactionType.Expense ? 'amount--expense' : 'amount--income')">
```

2023-03-20 19:45 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.scss
> +        .amount--0 { color: colors.$secondary-text; }
```suggestion
        .amount--zero { color: colors.$secondary-text; }
```

2023-03-20 19:45 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.ts
I've also noticed that when adding new transaction it is added to the bottom of the list ignoring the date of the transaction. Maybe you can also fix this as part of this PR instead creating another issue.

2023-03-20 19:45 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/transaction-editor/pages-wallet-transaction-editor.component.spec.ts
> +          it('0', () => {
```suggestion
        describe('validation errors', () => {
          it('should not show validation error if amount is equal to 0', () => {
```
Other test descriptions should be changed in similar way. `it` should describe what `should` happen. `describe` is just grouping a bunch of related tests together and label them.

2023-03-20 19:45 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/transaction-editor/pages-wallet-transaction-editor.component.ts
> +      if(!isNaN(value) && value >= 0) {
```suggestion
      if (!isNaN(value) && value >= 0) {
```

2023-03-22 18:51 UTC, purbanski-deftcode requested changes

2023-03-22 18:51 UTC, purbanski-deftcode commented on src/app/common/utils/sorts/common.util.sort..ts
> +export function sortByDate<T extends object, K extends KeysMatching<T, Date>>
And where is test for that? :trollface:

2023-03-22 18:51 UTC, purbanski-deftcode commented on src/app/common/utils/sorts/common.util.sort..ts
> +(array: T[], prop: K, desc = false): T[] {
```suggestion
(array: T[], prop: K, descending = false): T[] {
```

2023-03-22 18:51 UTC, purbanski-deftcode commented on src/app/common/utils/sorts/common.util.sort..ts
> +      (propAValue < propBValue ? 1 : -1);
Damn, first time I see such weird ternary, why not just:
```suggestion
    return (desc) ? (propAValue < propBValue ? -1 : 1) : (propAValue < propBValue ? 1 : -1);
```

2023-03-22 21:42 UTC, purbanski-deftcode approved these changes

2023-03-22 23:42 UTC, mirekgab approved these changes

2023-03-23 00:03 UTC, merged