feature: tuning up readme, node and yarn version checking
bycza-zagroda/track-expenses-app-frontend pull request #164
Opened 2023-08-01 13:10 UTC by AdrianRomanski

Please check if configuration process is working

2023-08-01 15:16 UTC, mirekgab requested changes

2023-08-01 15:16 UTC, mirekgab commented on README.md
> +- git clone: https://github.com/bycza-zagroda/track-expenses-app-frontend.git
```suggestion
- git clone https://github.com/bycza-zagroda/track-expenses-app-frontend.git
```

2023-08-12 10:43 UTC, AdrianRomanski commented on README.md
> +- git clone: https://github.com/bycza-zagroda/track-expenses-app-frontend.git
@mirekgab ready

2023-08-12 14:37 UTC, mirekgab approved these changes

2023-08-13 10:31 UTC, merged