feature/14-create-colors.scss file
bycza-zagroda/track-expenses-app-frontend pull request #24
Opened 2022-10-12 17:09 UTC by DagmaraSkorupska

2022-10-12 20:02 UTC, jkbkupczyk approved these changes
👍

2022-10-16 20:05 UTC, purbanski-deftcode commented
I don't quire understand a purpose of this. In the project we are using Angular Material which can have theme configured for the whole application. This is where we should start I think. And add global custom colors whenever those will be required by some other tickets.

2022-10-16 20:08 UTC, purbanski-deftcode requested changes

2022-10-16 20:08 UTC, purbanski-deftcode commented on src/assets/styles/colors.scss
> +$white: #ffffff;
All colors are following uppercase convention but this one is not. Maybe you can unify this.
Also like I said in other comment I'm not sure if those changes are even needed currently.

2022-10-16 20:08 UTC, purbanski-deftcode commented on src/assets/styles/colors.scss
> +$alertError: #FF5252;
There is `alert` or `error`, naming something `alertError` does not make much sense. Same for `successError` -> something can't be both a success and an error.

2022-10-19 19:21 UTC, closed without merging