Test/39 increase coverage for add/edit wallet related logic
bycza-zagroda/track-expenses-app-frontend pull request #42
Opened 2022-11-18 14:42 UTC by tomektomek321

2022-11-22 23:01 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +        { provide: DomainsWalletsGateway, useValue: mockService }
If in this file you want to test `DomainsWalletsGateway` then it should be a "real" one, you should not mock it with `mockService`. You always mock only dependencies of the service / component that you want to test. And only dependency that this gateway has is `HttpClient` so only it should be mocked.

Then it test you do for example `service.getWallets()` and you test if httpClient method `get` was called and with what parameters. You can check this article on how to test httpClient calls https://betterprogramming.pub/testing-http-requests-in-angular-with-httpclienttestingmodule-3880ceac74cf

2022-11-22 23:01 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.component.spec.ts
> +  describe('createWallet', () => {
Here you are testing `createWallet` but where do you actually call it? xD You are totally missing `component.createWallet` here before using `walletSubject.next` - besides that idea for the test was not bad.

2022-11-27 00:34 UTC, purbanski-deftcode requested changes

2022-11-27 00:34 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.service.ts
> +import { catchError, map, Observable, ObservableInput, of } from 'rxjs';
Please run `npm run lint`, you have 22 errors and 25 warnings to fix :) Including not used imports here.

2022-11-27 20:05 UTC, purbanski-deftcode requested changes

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    service = TestBed.get<DomainsWalletsGateway>(DomainsWalletsGateway);
You have linter issue here because you should use `.inject` instead `.get` as `.get` is deprecated. Not sure why your editor was not showing this to you :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.component.spec.ts
> +    myWalletsServiceMock = createSpyObj(PagesWalletsMyWalletsService.name, ['getMyWallets', 'createWallet', 'updateWallet']);
You have linter issue here because `createSpyObj` return `any`. You need to tell it what type it is mocking / returning like this `createSpyObj<PagesWAlletsMyWalletsService>()`.

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.service.spec.ts
> +    gatewayMock = createSpyObj(DomainsWalletsGateway.name, ['getWallets', 'createWallet', 'updateWallet']);
And here the same, you need to use generic `createSpyObj<T>`

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.component.spec.ts
> +
This test is still failing for two reasons:
- when we create component the `component.myWalletsData.data` is null instead of some array -> can be fixed by setting it to empty array at the beginning of this `it` block
- you need to use `.next` like on line 46 to emit value otherwise `.subscribe` inside `createWallet` will never fire

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +  const apiUrl: string = environment.remotePath + '/api/wallet';
if you can please rename `remotePath` to `apiUrl` :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +  const apiUrl: string = environment.remotePath + '/api/wallet';
Also to not repeat yourself in gateway and in test you should have this in some `domains.wallets.constants.ts` file. For example you can call it `export const API_WALLETS_URL`

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    walletResp = { name: 'Wallet 1', creationDate: '2022-10-22T09:47:52.595721658Z', id: 1 };
You are using this mock data in few places now. It would be cool to have a file like `domains.wallets.mocks.ts` and have it exported there and reused in tests.

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    it('should getWallets method return wallets', () => {
Those `it('something')` should be always easily read. For example I would change this one to `it('should call proper api url and return wallets data)` -> that way when you read it it is clear what is tested.

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    it('should createWallet method return wallet', () => {
Please try to improve those texts based on my previous comment :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    it('should updateWallet method return updated wallet', () => {
Please try to improve this text based on my previous comment :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallet.model.spec.ts
> +describe('MyWallet Class', () => {
Can be just `describe('MyWallet')`

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallet.model.spec.ts
> +    const wallet = new MyWallet({ id: 999, creationDate: '2022-10-23T09:47:52.595721658Z', name: 'wallet 5' });
For preparing data for tests most of the time we use `beforeEach` block. Like this:
```typescript
let wallet: MyWallet;

beforeEach(() => {
    wallet = new MyWallet(WALLET_RESP_MOCK);
});

it('bla bla', () => {});
```
 
It is basically fired before each `it` in `describe` block and creating new data before each test :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallet.model.spec.ts
> +    it('should return MyWallet for Create', () => {
I would change this to `it('should create new instance of the wallet')` :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallet.model.spec.ts
> +      const payload = MyWallet.create(wallet);
Please separate payload line from those two `expect` lines. Overall when writing test we separate them into three blocks according to AAA pattern: https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallet.model.spec.ts
> +  describe('create', () => {
What you should do is to create one `describe('create')` but inside it have two `it`s. Like:
`it('should create wallet when do data is provided')` and `it('should create wallet with data provided')`.

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.component.ts
> +    }, () => {
You can remove those error handlers for now. We will introduce them later when some pop ups are introduced. Also using it that way is deprecated. Please check in `ngOnInit` how `next` and `error` should be handled :)

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.service.spec.ts
> +  let walletRespForCreate: IWalletApiResponse;
Maybe better name would be `walletCreateResponse`

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.service.spec.ts
> +  let updatedWalletFromPayload: MyWallet;
Maybe better name would be just `updatedWallet`

2022-11-27 20:05 UTC, purbanski-deftcode commented on src/app/pages/wallets/my-wallets/pages-wallets-my-wallets.service.spec.ts
> +  let walletRespForUpdate: IWalletApiResponse;
Maybe better name would be `walletUpdateResponse`

2022-11-29 15:54 UTC, purbanski-deftcode requested changes

2022-11-29 15:54 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    let data: IWalletApiResponse;
This is basically the same what `walletResp`. Can't you reuse `walletResp`? :)

2022-11-29 15:54 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    let data: IWalletApiResponse;
Here you can also just reuse `walletResp` :)

2022-11-29 15:54 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.ts
> +  private apiUrl: string = API_WALLETS_URL;
I think you can just use in methods `API_WALLETS_URL`, you do not need this intermediate variable.

2022-11-29 15:54 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.spec.ts
> +    let data: IWalletPayload;
From what I saw you also prepared payload mock that you can reuse here.

2022-11-29 16:37 UTC, purbanski-deftcode approved these changes

2022-11-29 16:44 UTC, Iwona007 approved these changes

2022-11-29 16:44 UTC, merged