Notifications should disappear after some time
bycza-zagroda/track-expenses-app-frontend pull request #52
Opened 2022-12-19 11:47 UTC by tomektomek321

2022-12-19 19:32 UTC, purbanski-deftcode requested changes

2022-12-19 19:32 UTC, purbanski-deftcode commented on src/app/common/utils/system-notifications/system-notifications.service.ts
> +          duration: 1000 * SNACKBAR_DURATION_SECONDS,
It works but it breaks existing tests that need to be adjusted now.

2022-12-21 01:36 UTC, purbanski-deftcode approved these changes

2022-12-21 06:18 UTC, mirekgab approved these changes

2022-12-21 22:15 UTC, merged