Feature/67 sorting newly added wallets
bycza-zagroda/track-expenses-app-frontend pull request #68
Opened 2023-01-02 19:43 UTC by DawidStuzynski

2023-01-02 21:00 UTC, purbanski-deftcode requested changes

2023-01-02 21:00 UTC, purbanski-deftcode commented on src/app/domains/wallets/domains.wallets.gateway.ts
> +    return this.http.patch<IWalletApiResponse>(API_WALLETS_URL + `/${id}`, { name });
Should be ``${API_WALLETS_URL}/${id}``

2023-01-02 21:00 UTC, purbanski-deftcode commented on src/app/pages/wallets/management/pages-wallets-management.component.ts
> +        this.myWalletsData.data = [wallet, ...this.myWalletsData.data!];
You can just go with:
```typescript
this.myWalletsData.data = [wallet, ...this.myWalletsData.data!].sort(here_rest_of_the_code);
```

2023-01-02 21:00 UTC, purbanski-deftcode commented on src/app/pages/wallets/management/pages-wallets-management.component.ts
> +        this.myWalletsData.data = this.myWalletsData.data!.map(walletItem => {
Seems like we should also sort wallets when updating a wallet. If we rename a wallet the old position can be wrong and need to be adjusted.

2023-01-02 21:00 UTC, purbanski-deftcode commented
Closes #67

2023-01-03 18:05 UTC, purbanski-deftcode approved these changes

2023-01-03 18:32 UTC, mirekgab approved these changes

2023-01-03 18:32 UTC, merged