Fix loading indicator and add missing ones (#77)
bycza-zagroda/track-expenses-app-frontend pull request #89
Opened 2023-01-30 23:07 UTC by Bartexs

Closes #77 

---

I confirm that (check also those that do not apply to this PR):
- [X] New code is covered with tests and coverage requirements are met
- [X] All tests are passing
- [X] Build is not failing
- [X] Mobile version of new functionality is displayed properly
- [X] All linter issues are resolved
- [X] All conflicts are resolved and branch is rebased on top of the up-to-date parent branch
- [X] All issue requirements are implemented
- [X] At least two reviewers are assigned
- [X] I'm assigned as a assignee
- [X] PR is linked to the related issue

2023-01-31 18:17 UTC, purbanski-deftcode requested changes
You forgot also to do "Reduce size of the loading indicator for wallets list - lets go maybe with 30."

2023-01-31 18:17 UTC, purbanski-deftcode commented on src/app/pages/wallets/management/wallet-editor/pages-wallets-management-editor.service.ts
> +        wallet ? this.loadingSnackbarService.show('Updating wallet') : this.loadingSnackbarService.show('Saving wallet');
Because both updating wallet and creating wallet is basically "saving" wallet we can probably just show text "Saving wallet". I will adjust issue :)

2023-01-31 18:17 UTC, purbanski-deftcode commented on src/app/pages/wallets/management/wallet-editor/pages-wallets-management-editor.service.ts
> +        wallet ? this.loadingSnackbarService.show('Updating wallet') : this.loadingSnackbarService.show('Saving wallet');
This and hiding snackbar should be covered by test.

2023-01-31 18:17 UTC, purbanski-deftcode commented on src/app/common/loading-modal/loading-modal.component.scss
> +::ng-deep .custom-snackbar-class {
Probably better will be to create in `/assets/styles/` directory `components` and there file `snackbar.scss`. Then create a class there like `app-snackbar` or something similar. Those styles are not excatly styles of this component but we are overriding styles of angular material component so this should be global css class.

2023-02-01 22:10 UTC, purbanski-deftcode requested changes
Please run `npm run lint` and check and fix linter warnings/errors.
Also please run `npm run test:headless` and fix displayed warnings/errors.

2023-02-05 10:16 UTC, purbanski-deftcode requested changes
Please rebase on top of our develop and resolve conflicts

2023-02-05 21:44 UTC, purbanski-deftcode requested changes
Tests are failing

2023-02-05 22:31 UTC, purbanski-deftcode approved these changes

2023-02-06 07:10 UTC, mirekgab approved these changes

2023-02-06 08:29 UTC, merged