Delete Transaction
bycza-zagroda/track-expenses-app-frontend pull request #90
Opened 2023-02-01 12:53 UTC by tomektomek321

Closes #[HERE_ADD_ISSUE_NUMBER]

---

I confirm that (check also those that do not apply to this PR):
- [x] New code is covered with tests and coverage requirements are met
- [x] All tests are passing
- [x] Build is not failing
- [x] Mobile version of new functionality is displayed properly
- [x] All linter issues are resolved
- [x] All conflicts are resolved and branch is rebased on top of the up-to-date parent branch
- [x] All issue requirements are implemented
- [x] At least two reviewers are assigned
- [x] I'm assigned as a assignee
- [x] PR is linked to the related issue

2023-02-01 14:26 UTC, purbanski-deftcode requested changes

2023-02-01 14:26 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.ts
> +        this.systemNotificationsService.showNotification({ message: 'Some server error occured. Contact Administrator' });
Please also add similar notification after successful deletion of transaction.

2023-02-01 14:26 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.ts
> +          if(transactionItem.id === transaction.id) {
Bro, `return transactionItem.id !== transaction.id`

2023-02-01 22:13 UTC, purbanski-deftcode approved these changes

2023-02-02 05:08 UTC, mirekgab approved these changes

2023-02-02 07:31 UTC, merged