Task/79 improve wallet details view
bycza-zagroda/track-expenses-app-frontend pull request #97
Opened 2023-02-06 21:35 UTC by tomektomek321

Closes #[HERE_ADD_ISSUE_NUMBER]

---

I confirm that (check also those that do not apply to this PR):
- [ ] New code is covered with tests and coverage requirements are met
- [ ] All tests are passing
- [ ] Build is not failing
- [ ] Mobile version of new functionality is displayed properly
- [ ] All linter issues are resolved
- [ ] All conflicts are resolved and branch is rebased on top of the up-to-date parent branch
- [ ] All issue requirements are implemented
- [ ] At least two reviewers are assigned
- [ ] I'm assigned as a assignee
- [ ] PR is linked to the related issue

2023-02-06 22:09 UTC, purbanski-deftcode requested changes

2023-02-06 22:09 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.scss
> +@media only screen and (max-width: 500px) {
All looks good but you should use media queries in "opposite direction". First you should define styles for mobile and then when needed use `min-width` to change them for bigger and bigger resolutions :)

2023-02-06 22:09 UTC, purbanski-deftcode commented on src/app/pages/wallets/wallet-details/pages-wallet-details.component.html
>          <button mat-stroked-button color="primary" (click)="handleWalletEdit()">Edit</button>
I've checked how this looks now, and have one more requirement that I think will improve it a little more - to move buttons to the right on desktop:
![Track Expenses 2023-02-06 23-09-30](https://user-images.githubusercontent.com/16034577/217098891-d4605284-052e-4248-9255-53c3a6cbd95c.jpg)

2023-02-06 22:50 UTC, purbanski-deftcode approved these changes

2023-02-08 16:22 UTC, mirekgab approved these changes

2023-02-08 16:28 UTC, merged