Feature/handle 404 for wallet details
bycza-zagroda/track-expenses-app-frontend pull request #98
Opened 2023-02-08 16:55 UTC by Bartexs

Closes #[HERE_ADD_ISSUE_NUMBER]

---

I confirm that (check also those that do not apply to this PR):
- [X] New code is covered with tests and coverage requirements are met
- [X] All tests are passing
- [X] Build is not failing
- [X] Mobile version of new functionality is displayed properly
- [X] All linter issues are resolved
- [X] All conflicts are resolved and branch is rebased on top of the up-to-date parent branch
- [X] All issue requirements are implemented
- [X] At least two reviewers are assigned
- [X] I'm assigned as a assignee
- [X] PR is linked to the related issue

2023-02-08 21:17 UTC, purbanski-deftcode requested changes

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/pages/common/pages-not-found-page/pages-not-found-page.component.html
> +<div class="container not-found">
Path to this file should be `/pages/not-found`. Also for home it should be `/pages/home`, it should be the same or very similar in some way to routes we will use to easily find specific page.

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/pages/common/pages-not-found-page/pages-not-found-page.component.html
> +    <div class="app-logo-div">
I'm not sure if you need those divs. Probably you can have just:
```html
<img />
<h1></h1>
<p></p>
```

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/pages/common/pages-not-found-page/pages-not-found-page.component.scss
> +        font-size: 40px;
Lets go with much bigger size for h1 in that case. Lets go for 80px for h1, increase padding bottom to 25px and also you can have same font-sizes and padding for mobile and desktop.

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/pages/common/pages-not-found-page/pages-not-found-page.component.html
> +        <img class="app-logo" src="assets/images/logos/404-not-found-logo.svg" alt="404-Not-Found-Page-Logo"/>
Alt text for images should have meaning. It should not be dashed phrase. Here for example it can be "Image for 404 page"

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/common/utils/resolvers/pages-wallet-details.resolver.ts
> +    this.navigateErrorPageIfWalletNotFound(wallet);
In that case you should stop executing rest of the code as wallet will be `undefined` so `return new WalletsManagementItem(wallet)` does not make sense

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/common/utils/resolvers/pages-wallet-details.resolver.ts
> +      void this.router.navigate([ '/**' ], { skipLocationChange: true });
Why this `void` is needed?

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/common/utils/resolvers/pages-wallet-details.resolver.ts
> +  public navigateErrorPageIfWalletNotFound(wallet: IWalletApiResponse | undefined): void {
This should not be `public`, it won't be used outside of this class

2023-02-08 21:17 UTC, purbanski-deftcode commented on src/app/common/utils/resolvers/pages-wallet-details.resolver.spec.ts
> +        resolver.navigateErrorPageIfWalletNotFound(undefined);
You should not test `navigateErrorPageIfWalletNotFound` as this method should be private. You should test `resolve` method.

2023-02-10 15:56 UTC, purbanski-deftcode commented
Please add `text-align: center` for `<p>`:
![localhost_4200_wallets_44444(iPhone SE)](https://user-images.githubusercontent.com/16034577/218136609-b2c94666-8aea-4154-a7cc-c5daa4b09376.png)

2023-02-10 16:01 UTC, purbanski-deftcode requested changes

2023-02-10 16:01 UTC, purbanski-deftcode commented on src/app/common/utils/resolvers/pages-wallet-details.resolver.ts
> +      void this.router.navigate([ '/**' ], { skipLocationChange: true });
This `void` is not needed, just add `await` before `this.router.navigate` and you should not have any linter / TS errors.

2023-02-10 20:13 UTC, purbanski-deftcode approved these changes

2023-02-10 20:14 UTC, mirekgab approved these changes

2023-02-10 20:43 UTC, Iwona007 approved these changes

2023-02-10 21:10 UTC, merged